/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 .\public\Monitor.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Monitor(props) {
  const { nodes, materials } = useGLTF('/Monitor.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.5, 0.869, 1.856]}>
        <mesh geometry={nodes.Würfel002.geometry} material={materials['Monitor Base']} />
        <mesh geometry={nodes.Würfel002_1.geometry} material-color={"#36286b"} />
      </group>
      <group position={[0.5, -0.511, 2.5]}>
        <mesh geometry={nodes.Würfel003.geometry} material={materials.Tastaten} />
        <mesh geometry={nodes.Würfel003_1.geometry} material={materials['Tastatur unten']} />
      </group>
      {/*<mesh geometry={nodes.Fläche001.geometry} material={materials['Material.002']} scale={[7.249, 1.011, 1.659]} />*/}
      {/*<mesh geometry={nodes.Fläche.geometry} material={nodes.Fläche.material} position={[0, -1.995, 0]} scale={3.654} />*/}
    </group>
  )
}

useGLTF.preload('/Monitor.glb')
